name: "clean: History"

on:
  repository_dispatch:
    types: [clean]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write

env:
  REPO: ${{ github.repository_owner }}/AM
  BRANCH: main-clean

jobs:
  clean-history:
    name: "Clean history"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout AM"
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: main
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: "Find the last commit in main-clean"
        id: last_commit
        run: |
          # Get the last commit hash from the main-clean branch
          LAST_COMMIT=$(git rev-parse origin/${{ env.BRANCH }})
          echo "Last commit in main-clean: $LAST_COMMIT"
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV
      
      - name: "Find corresponding commit in main"
        id: find_commit
        run: |
          # Find the corresponding commit from main that matches the last commit in main-clean
          COMMIT_IN_MAIN=$(git merge-base origin/main ${{ env.LAST_COMMIT }})
          echo "Found matching commit in main: $COMMIT_IN_MAIN"
          echo "commit_in_main=$COMMIT_IN_MAIN" >> $GITHUB_ENV

      - name: "Checkout branch"
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "noreply@github.com"
          if git ls-remote --exit-code --heads origin "${{ env.BRANCH }}"; then
            git fetch origin "${{ env.BRANCH }}"
            git checkout "${{ env.BRANCH }}"
          else
            git checkout -b "${{ env.BRANCH }}"
          fi

      - name: "Apply changes from $BRANCH to main"
        run: |
          # Checkout to main branch
          git checkout main
          # Fetch latest updates
          git fetch origin
          # Get the diff between "${{ env.BRANCH }}" and main
          git diff ${{ env.COMMIT_IN_MAIN }}..${{ env.LAST_COMMIT }} > changes.diff
          # Apply the diff to the "${{ env.BRANCH }}" branch
          git apply changes.diff
          # Add and commit the changes
          git add .
          git commit -m "Apply changes from main"
          # Push the changes to "${{ env.BRANCH }}"
          git push origin "${{ env.BRANCH }}"

      - name: "Clean empty merge commits"
        run: |
          # Only clean up commits after the last known commit
          git filter-branch -f --commit-filter '
            if git show -s --format=%P $GIT_COMMIT | grep -q " "; then
              skip_commit "$@";
            else
              git commit-tree "$@";
            fi' HEAD || echo "No commits modified"

      - name: "Push changes"
        run: |
          if ! git diff --quiet; then
            git push --force origin HEAD:"${{ env.BRANCH }}"
          else
            echo "No changes to push"
          fi
